version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - media_volume:/code/media/
      - static_volume:/code/staticfiles/
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
    - '8080:8080'
    volumes:
      - ./frontend:/app/
    command: /bin/sh -c "quasar dev"

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=panel_user
      - POSTGRES_PASSWORD=p4n3l_p4ss!@
      - POSTGRES_DB=panel_db
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume:
