# Generated by Django 3.2.6 on 2022-04-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(max_length=100)),
                ('instance_id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('secret', models.CharField(max_length=48, unique=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('update_interval', models.IntegerField(default=15)),
                ('next_update', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('STOPPED', 'STOPPED'), ('ACTIVE', 'ACTIVE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='app.source')),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='app.fields')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='app.source')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='app.updates')),
            ],
        ),
        migrations.AddField(
            model_name='fields',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='app.source'),
        ),
    ]
