# Generated by Django 3.2.6 on 2022-05-04 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('access_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('connector', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.AlterModelOptions(
            name='fields',
            options={'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AlterModelOptions(
            name='updates',
            options={'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
        migrations.AlterModelOptions(
            name='values',
            options={'verbose_name': 'Value', 'verbose_name_plural': 'Values'},
        ),
        migrations.RenameField(
            model_name='values',
            old_name='value',
            new_name='last_value',
        ),
        migrations.AddField(
            model_name='updates',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='secret',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='source',
            name='credentials',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='app.credentials'),
            preserve_default=False,
        ),
    ]
