# Generated by Django 3.2.6 on 2022-05-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220504_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='message',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='updates',
            name='result',
        ),
        migrations.RemoveField(
            model_name='updates',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='last_error_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_error_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_try_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='last_try_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('IGNORED', 'IGNORED'), ('ERROR', 'ERROR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='updates',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='SourceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('IGNORED', 'IGNORED'), ('ERROR', 'ERROR')], max_length=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='app.source')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='app.updates')),
            ],
            options={
                'verbose_name': 'Source Update',
                'verbose_name_plural': 'Source Updates',
            },
        ),
    ]
