# Generated by Django 3.2.6 on 2022-05-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_sourceupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='code',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('update_alredy_running', 'update_alredy_running'), ('update_failed', 'update_failed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('success', 'SUCCESS'), ('ignored', 'IGNORED'), ('error', 'ERROR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='updates',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('error', 'success')], max_length=10),
        ),
    ]
