# Generated by Django 3.2.6 on 2022-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220506_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='last_error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('ignored', 'ignored'), ('error', 'error')], max_length=10),
        ),
        migrations.AlterField(
            model_name='updates',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('error', 'error')], max_length=10),
        ),
    ]
