# Generated by Django 3.2.6 on 2022-05-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220506_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('error', 'error')], max_length=10, null=True),
        ),
    ]
