# Generated by Django 3.2.6 on 2022-05-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_updates_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='code',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('update_already_running', 'update_already_running'), ('update_failed', 'update_failed')], max_length=100, null=True),
        ),
    ]
