# Generated by Django 3.2.6 on 2022-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='data',
        ),
        migrations.AddField(
            model_name='sourceupdate',
            name='data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
