# Generated by Django 3.2.6 on 2022-05-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220510_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='field',
        ),
        migrations.RemoveField(
            model_name='values',
            name='source',
        ),
        migrations.RemoveField(
            model_name='values',
            name='update',
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
        migrations.DeleteModel(
            name='Values',
        ),
    ]
