# Generated by Django 3.2.6 on 2022-05-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220518_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('artifact_instance', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='app.artifact')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='Metric_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Metric Type',
                'verbose_name_plural': 'Metric Types',
            },
        ),
        migrations.RenameModel(
            old_name='SourceUpdate',
            new_name='Source_Data',
        ),
        migrations.CreateModel(
            name='Metric_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='app.metric')),
                ('source_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_data', to='app.source_data')),
            ],
        ),
        migrations.AddField(
            model_name='metric',
            name='last_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='app.source_data'),
        ),
        migrations.AddField(
            model_name='metric',
            name='metric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='app.metric_types'),
        ),
        migrations.AddField(
            model_name='metric',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='app.source'),
        ),
    ]
