# Generated by Django 3.2.6 on 2022-06-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220519_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source_data',
            options={'verbose_name': 'Source Data', 'verbose_name_plural': 'Sources Data'},
        ),
        migrations.RemoveField(
            model_name='updates',
            name='code',
        ),
        migrations.AddField(
            model_name='source',
            name='last_update_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_update', to='app.updates'),
        ),
        migrations.AddField(
            model_name='source',
            name='remote_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='status_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='source_data',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='update_data', to='app.source'),
        ),
        migrations.AlterField(
            model_name='source_data',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources_data', to='app.updates'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('failed', 'failed'), ('running', 'running')], max_length=10, null=True),
        ),
    ]
