# Generated by Django 3.2.6 on 2022-06-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220601_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='last_update_id',
            new_name='last_update',
        ),
    ]
