# Generated by Django 3.2.6 on 2022-06-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_last_update_id_source_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='last_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='app.source_data'),
        ),
    ]
