# Generated by Django 3.2.6 on 2022-06-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_metric_last_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='binded_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='app.source'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='app.metric_types'),
        ),
    ]
