# Generated by Django 3.2.6 on 2022-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220603_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='remote_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
